### ISSUE TITLE
Muestra de contenido

### ISSUE THREAD

**Issue by matiasquevedo** [matiasquevedo/web_design#23]
1)Eliminar todo el contenido que tiene el sitio 
2)Agregar en el siguiente orden:
-Carousel de Imagenes (issue #22 )
-Grilla de Links
-Galeria de Imagenes masonry 
-Barra Video
-Barra de Sponsors

3)Verificar responsive

Sitio modelo https://www.android-kiosk.com/

**Comment by matiasquevedo** [comment]
![logo_aventura](https://user-images.githubusercontent.com/12038889/31894179-056f84f4-b7e4-11e7-8e72-ffe0be512ff6.png)

**Comment by Lucas-69** [comment]
https://themes.materializecss.com/pages/docs#
